#Data-Exploration

##Data-card Expectations
- 500K Rows, 8 Columns
- Negative Quantity values = cancelled transactions
- 'C' in transaction id = cancelled transactions
- Price should be > 0
- Every row should have a customer number

Below, I will test these expectations with actual data

In [1]:
import pandas as pd
df = pd.read_csv('../data/sales transaction v.4a.csv')
print(df.shape)
print(df.head(10))

(536350, 8)
  TransactionNo       Date ProductNo                          ProductName  \
0        581482  12/9/2019     22485        Set Of 2 Wooden Market Crates
1        581475  12/9/2019     22596  Christmas Star Wish List Chalkboard
2        581475  12/9/2019     23235             Storage Tin Vintage Leaf
3        581475  12/9/2019     23272    Tree T-Light Holder Willie Winkie
4        581475  12/9/2019     23239    Set Of 4 Knick Knack Tins Poppies
5        581475  12/9/2019     21705              Bag 500g Swirly Marbles
6        581475  12/9/2019     22118             Joy Wooden Block Letters
7        581475  12/9/2019     22119           Peace Wooden Block Letters
8        581475  12/9/2019     22217          T-Light Holder Hanging Lace
9        581475  12/9/2019     22216            T-Light Holder White Lace

   Price  Quantity  CustomerNo         Country
0  21.47        12     17490.0  United Kingdom
1  10.65        36     13069.0  United Kingdom
2  11.53        12     13069.0  United Kingdom
3  10.65        12     13069.0  United Kingdom
4  11.94         6     13069.0  United Kingdom
5  10.65        24     13069.0  United Kingdom
6  11.53        18     13069.0  United Kingdom
7  12.25        12     13069.0  United Kingdom
8  10.65        12     13069.0  United Kingdom
9  10.55        24     13069.0  United Kingdom

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 536350 entries, 0 to 536349
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TransactionNo  536350 non-null  str
 1   Date           536350 non-null  str
 2   ProductNo      536350 non-null  str
 3   ProductName    536350 non-null  str
 4   Price          536350 non-null  float64
 5   Quantity       536350 non-null  int64
 6   CustomerNo     536295 non-null  float64
 7   Country        536350 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 32.7 MB

In [3]:
df.isnull().sum()

TransactionNo     0
Date              0
ProductNo         0
ProductName       0
Price             0
Quantity          0
CustomerNo       55
Country           0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(5200)

In [5]:
#Date month/day/year or day/month/year?
parts = df["Date"].str.split("/", expand=True).astype(int)
print("first part max:", parts[0].max(), "| second part max:", parts[1].max())

first part max: 12 | second part max: 31

In [6]:
#real-time range?
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")
print(df["Date"].min(), df["Date"].max())

2018-12-01 00:00:00 2019-12-09 00:00:00

In [7]:
is_cancel = df["TransactionNo"].str.startswith("C")
neg_qty = df["Quantity"] < 0
pd.crosstab(is_cancel, neg_qty)

Quantity        False  True
TransactionNo
False          527765      0
True                0   8585

In [8]:
df[["Price", "Quantity"]].describe()

               Price       Quantity
count  536350.000000  536350.000000
mean       12.662182       9.919347
std         8.490450     216.662300
min         5.130000  -80995.000000
25%        10.990000       1.000000
50%        11.940000       3.000000
75%        14.090000      10.000000
max       660.620000   80995.000000

In [9]:

#fully duplicated rows
print(df.duplicated().sum())

5200

In [10]:
df[df["CustomerNo"].isnull()].head(10)

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
6511,C581406,2019-12-08,46000M,Polyester Filler Pad 45x45cm,6.19,-240,NaN,United Kingdom
6512,C581406,2019-12-08,46000S,Polyester Filler Pad 40x40cm,6.19,-300,NaN,United Kingdom
90098,C575153,2019-11-08,22947,Wooden Advent Calendar Red,44.25,-1,NaN,United Kingdom
102671,C574288,2019-11-03,22178,Victorian Glass Hanging T-Light,25.37,-1,NaN,United Kingdom
117263,C573180,2019-10-28,23048,Set Of 10 Lanterns Fairy Light Star,14.50,-1,NaN,United Kingdom
163160,C569495,2019-10-04,21843,Red Retrospot Cake Stand,21.47,-1,NaN,United Kingdom
190598,C567518,2019-09-20,22846,Bread Bin Diner Style Red,27.62,-1,NaN,United Kingdom
192284,C567518,2019-09-20,21871,Save The Planet Mug,11.94,-12,NaN,United Kingdom
242406,C563015,2019-08-11,46000M,Polyester Filler Pad 45x45cm,10.25,-160,NaN,United Kingdom
242407,C563015,2019-08-11,46000S,Polyester Filler Pad 40x40cm,10.25,-220,NaN,United Kingdom

In [11]:
print("Rows: ", len(df))
print("Transactions: ", df["TransactionNo"].nunique())
print("Customers: ", df["CustomerNo"].nunique())
print("Products: ", df["ProductNo"].nunique())

Rows:  536350
Transactions:  23204
Customers:  4738
Products:  3768

In [12]:
dups = df[df.duplicated(keep=False)]
dups.sort_values(list(df.columns)).head(10)

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
533729,536409,2018-12-01,21866,Union Jack Flag Luggage Tag,11.53,1,17908.0,United Kingdom
533752,536409,2018-12-01,21866,Union Jack Flag Luggage Tag,11.53,1,17908.0,United Kingdom
533720,536409,2018-12-01,22111,Scottie Dog Hot Water Bottle,15.32,1,17908.0,United Kingdom
533771,536409,2018-12-01,22111,Scottie Dog Hot Water Bottle,15.32,1,17908.0,United Kingdom
533724,536409,2018-12-01,22866,Hand Warmer Scotty Dog Design,12.40,1,17908.0,United Kingdom
533761,536409,2018-12-01,22866,Hand Warmer Scotty Dog Design,12.40,1,17908.0,United Kingdom
533756,536409,2018-12-01,22900,Set 2 Tea Towels I Love London,13.27,1,17908.0,United Kingdom
533769,536409,2018-12-01,22900,Set 2 Tea Towels I Love London,13.27,1,17908.0,United Kingdom
533808,536412,2018-12-01,21448,12 Daisy Pegs In Wood Box,11.94,1,17920.0,United Kingdom
533828,536412,2018-12-01,21448,12 Daisy Pegs In Wood Box,11.94,1,17920.0,United Kingdom

In [13]:
no_cust = df[df["CustomerNo"].isnull()]
print(no_cust["TransactionNo"].str.startswith("C").value_counts())

TransactionNo
True     54
False     1
Name: count, dtype: int64

In [14]:
df[df["Quantity"].abs() > 10000]

,TransactionNo,Date,ProductNo,ProductName,Price,Quantity,CustomerNo,Country
142,581483,2019-12-09,23843,Paper Craft Little Birdie,12.38,80995,16446.0,United Kingdom
1616,C581484,2019-12-09,23843,Paper Craft Little Birdie,6.19,-80995,16446.0,United Kingdom
41367,578841,2019-11-25,84826,Asstd Design 3d Paper Stickers,6.19,12540,13256.0,United Kingdom
473985,541431,2019-01-18,23166,Medium Ceramic Top Storage Jar,11.32,74215,12346.0,United Kingdom
475332,C541433,2019-01-18,23166,Medium Ceramic Top Storage Jar,11.32,-74215,12346.0,United Kingdom

In [15]:
df["Country"].value_counts().head(10)

Country
United Kingdom    485095
Germany            10675
France             10526
EIRE                8048
Belgium             2539
Spain               2430
Switzerland         2336
Netherlands         2330
Portugal            1848
Australia           1704
Name: count, dtype: int64